### ISSUE TITLE
Historical Future Order Book level 2 Data packages

### ISSUE THREAD

**Issue by Sippul** [binance/binance-public-data#268]
Hey, team,

While downloading the Historical Future Order Book level 2 Data via API, I found out that the order of data packaging has changed since May 28. Now the archive containing daily data contains updates and a snapshot for the end of the day. And in order to restore the orderbooks for the day, it is necessary to download the previous day as well to take snapshot from there.

Is this done intentionally or is it a data packing error?

With regards, Alex

**Comment by Sippul** [comment]
As an example, I can give the token ARKN

Traded since July 28

Updates have been going since 3 hours on July 28, first snap 23:59 on July 28.

No data for 27

**Comment by darienhuang** [comment]
Hi we did some update on our data. Before 23-05-28, the orderbook level 2 data has some gaps because it's using the api call and websocket depth update to do the data construction; After 23-05-28, we construct the level 2 data using internal log and guarantee no data gap. You can use the snapshot for the end of the day and the updates to construct orderbook for any time. Please check this faq for more detail: [updates](https://www.binance.com/en/support/faq/binance-futures-order-book-historical-data-e707685b4e0f408fa7c1b9ccd8ea7aa9). We will also soon remove the old endpoint and user can access this data using new endpoint.
