### ISSUE TITLE
where to get future history trades?

### ISSUE THREAD

**Issue by wljackhero** [binance/binance-public-data#93]
as [binance-public-data](https://github.com/binance/binance-public-data#trades-2) says:
```
All symbols are supported, the file format is:
<base_url>/data/spot/monthly/trades/<symbol_in_uppercase>/<symbol_in_uppercase>-trades-<year>-<month>.zip

e.g. the url BNBUSDT trades in 2019-01 is:
https://data.binance.vision/data/spot/monthly/trades/BNBUSDT/BNBUSDT-trades-2019-01.zip
```
I assume the future history trades download url would be:
https://data.binance.vision/data/future/monthly/trades/BNBUSDT/BNBUSDT-trades-2019-01.zip for month
https://data.binance.vision/data/future/daily/trades/BNBUSDT/BNBUSDT-trades-2019-01-01.zip for day

this works for spot, but not for future.

**Comment by 2pd** [comment]
`BNBUSDT` was not open for trade on this month.
You can call this enpdoint `GET fapi/v1/historicalTrades?symbol=xxxx&limit=1&from=1` to get the date of the first trade.

**Comment by wljackhero** [comment]
> `BNBUSDT` was not open for trade on this month. You can call this enpdoint `GET fapi/v1/historicalTrades?symbol=xxxx&limit=1&from=1` to get the date of the first trade.

i want to download future trade data
https://data.binance.vision/data/future/daily/trades/BTCUSDT/BTCUSDT-trades-2019-01-01.zip for day
https://data.binance.vision/data/future/monthly/trades/BTCUSDT/BTCUSDT-trades-2019-01.zip for month
both of the above urls don't work. 
where to get future trade data for day or month?

**Comment by 2pd** [comment]
You did get what I said.
There is no trade for you to download until the symbol is open for trade. Please check the date of first trade from the endpoint I mentioned above.

**Comment by yohplala** [comment]
Hello,

2 more points:
 - @wljackhero : for daily data, only the last 35 days are present, otherwise, report to monthly data. (as per doc: _Downloads all monthly and daily(for past 35 days)_ [here](https://github.com/binance/binance-public-data/tree/master/python).

 - @2pd : I tried to run this command (based on what you indicate) and I have this return:
 `https://fapi.binance.com/fapi/v1/historicalTrades?symbol=BTCUSDTx&limit=1&from=1`
returns:
`{"code":-2014,"msg":"API-key format invalid."}`

Having a check in Binance API doc, it says to use `fromId` instead of `from`. ([here](https://binance-docs.github.io/apidocs/futures/en/#old-trades-lookup-market_data)), but even though, I still have the same message:
 `https://fapi.binance.com/fapi/v1/historicalTrades?symbol=BTCUSDT&limit=1&fromId=1`
returns:
`{"code":-2014,"msg":"API-key format invalid."}`

Please, what am I doing wrong?
Thanks for your help,
Bests,

**Comment by yohplala** [comment]
Ah, I think I am being silly. Is it not a public API? It needs an API key?
